# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.5.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.5.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/sakunthalapanditharatne/Documents/Opensource/cgal-swig-bindings

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/sakunthalapanditharatne/Documents/Opensource/cgal-swig-bindings

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/local/Cellar/cmake/3.5.2/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.5.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.5.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.5.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.5.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.5.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/sakunthalapanditharatne/Documents/Opensource/cgal-swig-bindings/CMakeFiles /Users/sakunthalapanditharatne/Documents/Opensource/cgal-swig-bindings/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/sakunthalapanditharatne/Documents/Opensource/cgal-swig-bindings/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named _CGAL_Kernel

# Build rule for target.
_CGAL_Kernel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 _CGAL_Kernel
.PHONY : _CGAL_Kernel

# fast build rule for target.
_CGAL_Kernel/fast:
	$(MAKE) -f SWIG_CGAL/Kernel/CMakeFiles/_CGAL_Kernel.dir/build.make SWIG_CGAL/Kernel/CMakeFiles/_CGAL_Kernel.dir/build
.PHONY : _CGAL_Kernel/fast

#=============================================================================
# Target rules for targets named CGAL_Kernel

# Build rule for target.
CGAL_Kernel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CGAL_Kernel
.PHONY : CGAL_Kernel

# fast build rule for target.
CGAL_Kernel/fast:
	$(MAKE) -f SWIG_CGAL/Kernel/CMakeFiles/CGAL_Kernel.dir/build.make SWIG_CGAL/Kernel/CMakeFiles/CGAL_Kernel.dir/build
.PHONY : CGAL_Kernel/fast

#=============================================================================
# Target rules for targets named CGAL_Kernel_cpp

# Build rule for target.
CGAL_Kernel_cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CGAL_Kernel_cpp
.PHONY : CGAL_Kernel_cpp

# fast build rule for target.
CGAL_Kernel_cpp/fast:
	$(MAKE) -f SWIG_CGAL/Kernel/CMakeFiles/CGAL_Kernel_cpp.dir/build.make SWIG_CGAL/Kernel/CMakeFiles/CGAL_Kernel_cpp.dir/build
.PHONY : CGAL_Kernel_cpp/fast

#=============================================================================
# Target rules for targets named CGAL_Java_cpp

# Build rule for target.
CGAL_Java_cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CGAL_Java_cpp
.PHONY : CGAL_Java_cpp

# fast build rule for target.
CGAL_Java_cpp/fast:
	$(MAKE) -f SWIG_CGAL/Java/CMakeFiles/CGAL_Java_cpp.dir/build.make SWIG_CGAL/Java/CMakeFiles/CGAL_Java_cpp.dir/build
.PHONY : CGAL_Java_cpp/fast

#=============================================================================
# Target rules for targets named CGAL_Java

# Build rule for target.
CGAL_Java: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CGAL_Java
.PHONY : CGAL_Java

# fast build rule for target.
CGAL_Java/fast:
	$(MAKE) -f SWIG_CGAL/Java/CMakeFiles/CGAL_Java.dir/build.make SWIG_CGAL/Java/CMakeFiles/CGAL_Java.dir/build
.PHONY : CGAL_Java/fast

#=============================================================================
# Target rules for targets named _CGAL_Triangulation_3

# Build rule for target.
_CGAL_Triangulation_3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 _CGAL_Triangulation_3
.PHONY : _CGAL_Triangulation_3

# fast build rule for target.
_CGAL_Triangulation_3/fast:
	$(MAKE) -f SWIG_CGAL/Triangulation_3/CMakeFiles/_CGAL_Triangulation_3.dir/build.make SWIG_CGAL/Triangulation_3/CMakeFiles/_CGAL_Triangulation_3.dir/build
.PHONY : _CGAL_Triangulation_3/fast

#=============================================================================
# Target rules for targets named CGAL_Triangulation_3

# Build rule for target.
CGAL_Triangulation_3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CGAL_Triangulation_3
.PHONY : CGAL_Triangulation_3

# fast build rule for target.
CGAL_Triangulation_3/fast:
	$(MAKE) -f SWIG_CGAL/Triangulation_3/CMakeFiles/CGAL_Triangulation_3.dir/build.make SWIG_CGAL/Triangulation_3/CMakeFiles/CGAL_Triangulation_3.dir/build
.PHONY : CGAL_Triangulation_3/fast

#=============================================================================
# Target rules for targets named CGAL_Triangulation_3_cpp

# Build rule for target.
CGAL_Triangulation_3_cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CGAL_Triangulation_3_cpp
.PHONY : CGAL_Triangulation_3_cpp

# fast build rule for target.
CGAL_Triangulation_3_cpp/fast:
	$(MAKE) -f SWIG_CGAL/Triangulation_3/CMakeFiles/CGAL_Triangulation_3_cpp.dir/build.make SWIG_CGAL/Triangulation_3/CMakeFiles/CGAL_Triangulation_3_cpp.dir/build
.PHONY : CGAL_Triangulation_3_cpp/fast

#=============================================================================
# Target rules for targets named _CGAL_Triangulation_2

# Build rule for target.
_CGAL_Triangulation_2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 _CGAL_Triangulation_2
.PHONY : _CGAL_Triangulation_2

# fast build rule for target.
_CGAL_Triangulation_2/fast:
	$(MAKE) -f SWIG_CGAL/Triangulation_2/CMakeFiles/_CGAL_Triangulation_2.dir/build.make SWIG_CGAL/Triangulation_2/CMakeFiles/_CGAL_Triangulation_2.dir/build
.PHONY : _CGAL_Triangulation_2/fast

#=============================================================================
# Target rules for targets named CGAL_Triangulation_2

# Build rule for target.
CGAL_Triangulation_2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CGAL_Triangulation_2
.PHONY : CGAL_Triangulation_2

# fast build rule for target.
CGAL_Triangulation_2/fast:
	$(MAKE) -f SWIG_CGAL/Triangulation_2/CMakeFiles/CGAL_Triangulation_2.dir/build.make SWIG_CGAL/Triangulation_2/CMakeFiles/CGAL_Triangulation_2.dir/build
.PHONY : CGAL_Triangulation_2/fast

#=============================================================================
# Target rules for targets named CGAL_Triangulation_2_cpp

# Build rule for target.
CGAL_Triangulation_2_cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CGAL_Triangulation_2_cpp
.PHONY : CGAL_Triangulation_2_cpp

# fast build rule for target.
CGAL_Triangulation_2_cpp/fast:
	$(MAKE) -f SWIG_CGAL/Triangulation_2/CMakeFiles/CGAL_Triangulation_2_cpp.dir/build.make SWIG_CGAL/Triangulation_2/CMakeFiles/CGAL_Triangulation_2_cpp.dir/build
.PHONY : CGAL_Triangulation_2_cpp/fast

#=============================================================================
# Target rules for targets named _CGAL_Polyhedron_3

# Build rule for target.
_CGAL_Polyhedron_3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 _CGAL_Polyhedron_3
.PHONY : _CGAL_Polyhedron_3

# fast build rule for target.
_CGAL_Polyhedron_3/fast:
	$(MAKE) -f SWIG_CGAL/Polyhedron_3/CMakeFiles/_CGAL_Polyhedron_3.dir/build.make SWIG_CGAL/Polyhedron_3/CMakeFiles/_CGAL_Polyhedron_3.dir/build
.PHONY : _CGAL_Polyhedron_3/fast

#=============================================================================
# Target rules for targets named CGAL_Polyhedron_3

# Build rule for target.
CGAL_Polyhedron_3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CGAL_Polyhedron_3
.PHONY : CGAL_Polyhedron_3

# fast build rule for target.
CGAL_Polyhedron_3/fast:
	$(MAKE) -f SWIG_CGAL/Polyhedron_3/CMakeFiles/CGAL_Polyhedron_3.dir/build.make SWIG_CGAL/Polyhedron_3/CMakeFiles/CGAL_Polyhedron_3.dir/build
.PHONY : CGAL_Polyhedron_3/fast

#=============================================================================
# Target rules for targets named CGAL_Alpha_shape_2

# Build rule for target.
CGAL_Alpha_shape_2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CGAL_Alpha_shape_2
.PHONY : CGAL_Alpha_shape_2

# fast build rule for target.
CGAL_Alpha_shape_2/fast:
	$(MAKE) -f SWIG_CGAL/Alpha_shape_2/CMakeFiles/CGAL_Alpha_shape_2.dir/build.make SWIG_CGAL/Alpha_shape_2/CMakeFiles/CGAL_Alpha_shape_2.dir/build
.PHONY : CGAL_Alpha_shape_2/fast

#=============================================================================
# Target rules for targets named _CGAL_Alpha_shape_2

# Build rule for target.
_CGAL_Alpha_shape_2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 _CGAL_Alpha_shape_2
.PHONY : _CGAL_Alpha_shape_2

# fast build rule for target.
_CGAL_Alpha_shape_2/fast:
	$(MAKE) -f SWIG_CGAL/Alpha_shape_2/CMakeFiles/_CGAL_Alpha_shape_2.dir/build.make SWIG_CGAL/Alpha_shape_2/CMakeFiles/_CGAL_Alpha_shape_2.dir/build
.PHONY : _CGAL_Alpha_shape_2/fast

#=============================================================================
# Target rules for targets named CGAL_Alpha_shape_2_cpp

# Build rule for target.
CGAL_Alpha_shape_2_cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CGAL_Alpha_shape_2_cpp
.PHONY : CGAL_Alpha_shape_2_cpp

# fast build rule for target.
CGAL_Alpha_shape_2_cpp/fast:
	$(MAKE) -f SWIG_CGAL/Alpha_shape_2/CMakeFiles/CGAL_Alpha_shape_2_cpp.dir/build.make SWIG_CGAL/Alpha_shape_2/CMakeFiles/CGAL_Alpha_shape_2_cpp.dir/build
.PHONY : CGAL_Alpha_shape_2_cpp/fast

#=============================================================================
# Target rules for targets named CGAL_Spatial_searching

# Build rule for target.
CGAL_Spatial_searching: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CGAL_Spatial_searching
.PHONY : CGAL_Spatial_searching

# fast build rule for target.
CGAL_Spatial_searching/fast:
	$(MAKE) -f SWIG_CGAL/Spatial_searching/CMakeFiles/CGAL_Spatial_searching.dir/build.make SWIG_CGAL/Spatial_searching/CMakeFiles/CGAL_Spatial_searching.dir/build
.PHONY : CGAL_Spatial_searching/fast

#=============================================================================
# Target rules for targets named _CGAL_Spatial_searching

# Build rule for target.
_CGAL_Spatial_searching: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 _CGAL_Spatial_searching
.PHONY : _CGAL_Spatial_searching

# fast build rule for target.
_CGAL_Spatial_searching/fast:
	$(MAKE) -f SWIG_CGAL/Spatial_searching/CMakeFiles/_CGAL_Spatial_searching.dir/build.make SWIG_CGAL/Spatial_searching/CMakeFiles/_CGAL_Spatial_searching.dir/build
.PHONY : _CGAL_Spatial_searching/fast

#=============================================================================
# Target rules for targets named _CGAL_AABB_tree

# Build rule for target.
_CGAL_AABB_tree: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 _CGAL_AABB_tree
.PHONY : _CGAL_AABB_tree

# fast build rule for target.
_CGAL_AABB_tree/fast:
	$(MAKE) -f SWIG_CGAL/AABB_tree/CMakeFiles/_CGAL_AABB_tree.dir/build.make SWIG_CGAL/AABB_tree/CMakeFiles/_CGAL_AABB_tree.dir/build
.PHONY : _CGAL_AABB_tree/fast

#=============================================================================
# Target rules for targets named CGAL_AABB_tree

# Build rule for target.
CGAL_AABB_tree: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CGAL_AABB_tree
.PHONY : CGAL_AABB_tree

# fast build rule for target.
CGAL_AABB_tree/fast:
	$(MAKE) -f SWIG_CGAL/AABB_tree/CMakeFiles/CGAL_AABB_tree.dir/build.make SWIG_CGAL/AABB_tree/CMakeFiles/CGAL_AABB_tree.dir/build
.PHONY : CGAL_AABB_tree/fast

#=============================================================================
# Target rules for targets named CGAL_AABB_tree_cpp

# Build rule for target.
CGAL_AABB_tree_cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CGAL_AABB_tree_cpp
.PHONY : CGAL_AABB_tree_cpp

# fast build rule for target.
CGAL_AABB_tree_cpp/fast:
	$(MAKE) -f SWIG_CGAL/AABB_tree/CMakeFiles/CGAL_AABB_tree_cpp.dir/build.make SWIG_CGAL/AABB_tree/CMakeFiles/CGAL_AABB_tree_cpp.dir/build
.PHONY : CGAL_AABB_tree_cpp/fast

#=============================================================================
# Target rules for targets named _CGAL_Surface_mesher

# Build rule for target.
_CGAL_Surface_mesher: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 _CGAL_Surface_mesher
.PHONY : _CGAL_Surface_mesher

# fast build rule for target.
_CGAL_Surface_mesher/fast:
	$(MAKE) -f SWIG_CGAL/Surface_mesher/CMakeFiles/_CGAL_Surface_mesher.dir/build.make SWIG_CGAL/Surface_mesher/CMakeFiles/_CGAL_Surface_mesher.dir/build
.PHONY : _CGAL_Surface_mesher/fast

#=============================================================================
# Target rules for targets named CGAL_Surface_mesher

# Build rule for target.
CGAL_Surface_mesher: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CGAL_Surface_mesher
.PHONY : CGAL_Surface_mesher

# fast build rule for target.
CGAL_Surface_mesher/fast:
	$(MAKE) -f SWIG_CGAL/Surface_mesher/CMakeFiles/CGAL_Surface_mesher.dir/build.make SWIG_CGAL/Surface_mesher/CMakeFiles/CGAL_Surface_mesher.dir/build
.PHONY : CGAL_Surface_mesher/fast

#=============================================================================
# Target rules for targets named CGAL_Surface_mesher_cpp

# Build rule for target.
CGAL_Surface_mesher_cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CGAL_Surface_mesher_cpp
.PHONY : CGAL_Surface_mesher_cpp

# fast build rule for target.
CGAL_Surface_mesher_cpp/fast:
	$(MAKE) -f SWIG_CGAL/Surface_mesher/CMakeFiles/CGAL_Surface_mesher_cpp.dir/build.make SWIG_CGAL/Surface_mesher/CMakeFiles/CGAL_Surface_mesher_cpp.dir/build
.PHONY : CGAL_Surface_mesher_cpp/fast

#=============================================================================
# Target rules for targets named _CGAL_Mesh_3

# Build rule for target.
_CGAL_Mesh_3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 _CGAL_Mesh_3
.PHONY : _CGAL_Mesh_3

# fast build rule for target.
_CGAL_Mesh_3/fast:
	$(MAKE) -f SWIG_CGAL/Mesh_3/CMakeFiles/_CGAL_Mesh_3.dir/build.make SWIG_CGAL/Mesh_3/CMakeFiles/_CGAL_Mesh_3.dir/build
.PHONY : _CGAL_Mesh_3/fast

#=============================================================================
# Target rules for targets named CGAL_Mesh_3

# Build rule for target.
CGAL_Mesh_3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CGAL_Mesh_3
.PHONY : CGAL_Mesh_3

# fast build rule for target.
CGAL_Mesh_3/fast:
	$(MAKE) -f SWIG_CGAL/Mesh_3/CMakeFiles/CGAL_Mesh_3.dir/build.make SWIG_CGAL/Mesh_3/CMakeFiles/CGAL_Mesh_3.dir/build
.PHONY : CGAL_Mesh_3/fast

#=============================================================================
# Target rules for targets named CGAL_Mesh_3_cpp

# Build rule for target.
CGAL_Mesh_3_cpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CGAL_Mesh_3_cpp
.PHONY : CGAL_Mesh_3_cpp

# fast build rule for target.
CGAL_Mesh_3_cpp/fast:
	$(MAKE) -f SWIG_CGAL/Mesh_3/CMakeFiles/CGAL_Mesh_3_cpp.dir/build.make SWIG_CGAL/Mesh_3/CMakeFiles/CGAL_Mesh_3_cpp.dir/build
.PHONY : CGAL_Mesh_3_cpp/fast

#=============================================================================
# Target rules for targets named _CGAL_Mesh_2

# Build rule for target.
_CGAL_Mesh_2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 _CGAL_Mesh_2
.PHONY : _CGAL_Mesh_2

# fast build rule for target.
_CGAL_Mesh_2/fast:
	$(MAKE) -f SWIG_CGAL/Mesh_2/CMakeFiles/_CGAL_Mesh_2.dir/build.make SWIG_CGAL/Mesh_2/CMakeFiles/_CGAL_Mesh_2.dir/build
.PHONY : _CGAL_Mesh_2/fast

#=============================================================================
# Target rules for targets named CGAL_Mesh_2

# Build rule for target.
CGAL_Mesh_2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CGAL_Mesh_2
.PHONY : CGAL_Mesh_2

# fast build rule for target.
CGAL_Mesh_2/fast:
	$(MAKE) -f SWIG_CGAL/Mesh_2/CMakeFiles/CGAL_Mesh_2.dir/build.make SWIG_CGAL/Mesh_2/CMakeFiles/CGAL_Mesh_2.dir/build
.PHONY : CGAL_Mesh_2/fast

#=============================================================================
# Target rules for targets named _CGAL_Interpolation

# Build rule for target.
_CGAL_Interpolation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 _CGAL_Interpolation
.PHONY : _CGAL_Interpolation

# fast build rule for target.
_CGAL_Interpolation/fast:
	$(MAKE) -f SWIG_CGAL/Interpolation/CMakeFiles/_CGAL_Interpolation.dir/build.make SWIG_CGAL/Interpolation/CMakeFiles/_CGAL_Interpolation.dir/build
.PHONY : _CGAL_Interpolation/fast

#=============================================================================
# Target rules for targets named CGAL_Interpolation

# Build rule for target.
CGAL_Interpolation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CGAL_Interpolation
.PHONY : CGAL_Interpolation

# fast build rule for target.
CGAL_Interpolation/fast:
	$(MAKE) -f SWIG_CGAL/Interpolation/CMakeFiles/CGAL_Interpolation.dir/build.make SWIG_CGAL/Interpolation/CMakeFiles/CGAL_Interpolation.dir/build
.PHONY : CGAL_Interpolation/fast

#=============================================================================
# Target rules for targets named CGAL_Convex_hull_2

# Build rule for target.
CGAL_Convex_hull_2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CGAL_Convex_hull_2
.PHONY : CGAL_Convex_hull_2

# fast build rule for target.
CGAL_Convex_hull_2/fast:
	$(MAKE) -f SWIG_CGAL/Convex_hull_2/CMakeFiles/CGAL_Convex_hull_2.dir/build.make SWIG_CGAL/Convex_hull_2/CMakeFiles/CGAL_Convex_hull_2.dir/build
.PHONY : CGAL_Convex_hull_2/fast

#=============================================================================
# Target rules for targets named _CGAL_Convex_hull_2

# Build rule for target.
_CGAL_Convex_hull_2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 _CGAL_Convex_hull_2
.PHONY : _CGAL_Convex_hull_2

# fast build rule for target.
_CGAL_Convex_hull_2/fast:
	$(MAKE) -f SWIG_CGAL/Convex_hull_2/CMakeFiles/_CGAL_Convex_hull_2.dir/build.make SWIG_CGAL/Convex_hull_2/CMakeFiles/_CGAL_Convex_hull_2.dir/build
.PHONY : _CGAL_Convex_hull_2/fast

#=============================================================================
# Target rules for targets named CGAL_Voronoi_diagram_2

# Build rule for target.
CGAL_Voronoi_diagram_2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CGAL_Voronoi_diagram_2
.PHONY : CGAL_Voronoi_diagram_2

# fast build rule for target.
CGAL_Voronoi_diagram_2/fast:
	$(MAKE) -f SWIG_CGAL/Voronoi_diagram_2/CMakeFiles/CGAL_Voronoi_diagram_2.dir/build.make SWIG_CGAL/Voronoi_diagram_2/CMakeFiles/CGAL_Voronoi_diagram_2.dir/build
.PHONY : CGAL_Voronoi_diagram_2/fast

#=============================================================================
# Target rules for targets named _CGAL_Voronoi_diagram_2

# Build rule for target.
_CGAL_Voronoi_diagram_2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 _CGAL_Voronoi_diagram_2
.PHONY : _CGAL_Voronoi_diagram_2

# fast build rule for target.
_CGAL_Voronoi_diagram_2/fast:
	$(MAKE) -f SWIG_CGAL/Voronoi_diagram_2/CMakeFiles/_CGAL_Voronoi_diagram_2.dir/build.make SWIG_CGAL/Voronoi_diagram_2/CMakeFiles/_CGAL_Voronoi_diagram_2.dir/build
.PHONY : _CGAL_Voronoi_diagram_2/fast

#=============================================================================
# Target rules for targets named _CGAL_HalfedgeDS

# Build rule for target.
_CGAL_HalfedgeDS: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 _CGAL_HalfedgeDS
.PHONY : _CGAL_HalfedgeDS

# fast build rule for target.
_CGAL_HalfedgeDS/fast:
	$(MAKE) -f SWIG_CGAL/HalfedgeDS/CMakeFiles/_CGAL_HalfedgeDS.dir/build.make SWIG_CGAL/HalfedgeDS/CMakeFiles/_CGAL_HalfedgeDS.dir/build
.PHONY : _CGAL_HalfedgeDS/fast

#=============================================================================
# Target rules for targets named CGAL_HalfedgeDS

# Build rule for target.
CGAL_HalfedgeDS: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CGAL_HalfedgeDS
.PHONY : CGAL_HalfedgeDS

# fast build rule for target.
CGAL_HalfedgeDS/fast:
	$(MAKE) -f SWIG_CGAL/HalfedgeDS/CMakeFiles/CGAL_HalfedgeDS.dir/build.make SWIG_CGAL/HalfedgeDS/CMakeFiles/CGAL_HalfedgeDS.dir/build
.PHONY : CGAL_HalfedgeDS/fast

#=============================================================================
# Target rules for targets named _CGAL_Point_set_processing_3

# Build rule for target.
_CGAL_Point_set_processing_3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 _CGAL_Point_set_processing_3
.PHONY : _CGAL_Point_set_processing_3

# fast build rule for target.
_CGAL_Point_set_processing_3/fast:
	$(MAKE) -f SWIG_CGAL/Point_set_processing_3/CMakeFiles/_CGAL_Point_set_processing_3.dir/build.make SWIG_CGAL/Point_set_processing_3/CMakeFiles/_CGAL_Point_set_processing_3.dir/build
.PHONY : _CGAL_Point_set_processing_3/fast

#=============================================================================
# Target rules for targets named CGAL_Point_set_processing_3

# Build rule for target.
CGAL_Point_set_processing_3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CGAL_Point_set_processing_3
.PHONY : CGAL_Point_set_processing_3

# fast build rule for target.
CGAL_Point_set_processing_3/fast:
	$(MAKE) -f SWIG_CGAL/Point_set_processing_3/CMakeFiles/CGAL_Point_set_processing_3.dir/build.make SWIG_CGAL/Point_set_processing_3/CMakeFiles/CGAL_Point_set_processing_3.dir/build
.PHONY : CGAL_Point_set_processing_3/fast

#=============================================================================
# Target rules for targets named _CGAL_Box_intersection_d

# Build rule for target.
_CGAL_Box_intersection_d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 _CGAL_Box_intersection_d
.PHONY : _CGAL_Box_intersection_d

# fast build rule for target.
_CGAL_Box_intersection_d/fast:
	$(MAKE) -f SWIG_CGAL/Box_intersection_d/CMakeFiles/_CGAL_Box_intersection_d.dir/build.make SWIG_CGAL/Box_intersection_d/CMakeFiles/_CGAL_Box_intersection_d.dir/build
.PHONY : _CGAL_Box_intersection_d/fast

#=============================================================================
# Target rules for targets named CGAL_Box_intersection_d

# Build rule for target.
CGAL_Box_intersection_d: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CGAL_Box_intersection_d
.PHONY : CGAL_Box_intersection_d

# fast build rule for target.
CGAL_Box_intersection_d/fast:
	$(MAKE) -f SWIG_CGAL/Box_intersection_d/CMakeFiles/CGAL_Box_intersection_d.dir/build.make SWIG_CGAL/Box_intersection_d/CMakeFiles/CGAL_Box_intersection_d.dir/build
.PHONY : CGAL_Box_intersection_d/fast

#=============================================================================
# Target rules for targets named _CGAL_Polygon_mesh_processing

# Build rule for target.
_CGAL_Polygon_mesh_processing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 _CGAL_Polygon_mesh_processing
.PHONY : _CGAL_Polygon_mesh_processing

# fast build rule for target.
_CGAL_Polygon_mesh_processing/fast:
	$(MAKE) -f SWIG_CGAL/Polygon_mesh_processing/CMakeFiles/_CGAL_Polygon_mesh_processing.dir/build.make SWIG_CGAL/Polygon_mesh_processing/CMakeFiles/_CGAL_Polygon_mesh_processing.dir/build
.PHONY : _CGAL_Polygon_mesh_processing/fast

#=============================================================================
# Target rules for targets named CGAL_Polygon_mesh_processing

# Build rule for target.
CGAL_Polygon_mesh_processing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CGAL_Polygon_mesh_processing
.PHONY : CGAL_Polygon_mesh_processing

# fast build rule for target.
CGAL_Polygon_mesh_processing/fast:
	$(MAKE) -f SWIG_CGAL/Polygon_mesh_processing/CMakeFiles/CGAL_Polygon_mesh_processing.dir/build.make SWIG_CGAL/Polygon_mesh_processing/CMakeFiles/CGAL_Polygon_mesh_processing.dir/build
.PHONY : CGAL_Polygon_mesh_processing/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... test"
	@echo "... install/local"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... _CGAL_Kernel"
	@echo "... CGAL_Kernel"
	@echo "... CGAL_Kernel_cpp"
	@echo "... CGAL_Java_cpp"
	@echo "... CGAL_Java"
	@echo "... _CGAL_Triangulation_3"
	@echo "... CGAL_Triangulation_3"
	@echo "... CGAL_Triangulation_3_cpp"
	@echo "... _CGAL_Triangulation_2"
	@echo "... CGAL_Triangulation_2"
	@echo "... CGAL_Triangulation_2_cpp"
	@echo "... _CGAL_Polyhedron_3"
	@echo "... CGAL_Polyhedron_3"
	@echo "... CGAL_Alpha_shape_2"
	@echo "... _CGAL_Alpha_shape_2"
	@echo "... CGAL_Alpha_shape_2_cpp"
	@echo "... CGAL_Spatial_searching"
	@echo "... _CGAL_Spatial_searching"
	@echo "... _CGAL_AABB_tree"
	@echo "... CGAL_AABB_tree"
	@echo "... CGAL_AABB_tree_cpp"
	@echo "... _CGAL_Surface_mesher"
	@echo "... CGAL_Surface_mesher"
	@echo "... CGAL_Surface_mesher_cpp"
	@echo "... _CGAL_Mesh_3"
	@echo "... CGAL_Mesh_3"
	@echo "... CGAL_Mesh_3_cpp"
	@echo "... _CGAL_Mesh_2"
	@echo "... CGAL_Mesh_2"
	@echo "... _CGAL_Interpolation"
	@echo "... CGAL_Interpolation"
	@echo "... CGAL_Convex_hull_2"
	@echo "... _CGAL_Convex_hull_2"
	@echo "... CGAL_Voronoi_diagram_2"
	@echo "... _CGAL_Voronoi_diagram_2"
	@echo "... _CGAL_HalfedgeDS"
	@echo "... CGAL_HalfedgeDS"
	@echo "... _CGAL_Point_set_processing_3"
	@echo "... CGAL_Point_set_processing_3"
	@echo "... _CGAL_Box_intersection_d"
	@echo "... CGAL_Box_intersection_d"
	@echo "... _CGAL_Polygon_mesh_processing"
	@echo "... CGAL_Polygon_mesh_processing"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

